public class LeadTriggerHandler {
	
    /*public static void updateLeadStatus(List<Lead> newlist){
        for(Lead leadRec : newlist){
            leadRec.Status = 'Working - Contacted';
        }
    }*/
    
    /*public static void updateLead(List<Lead> newlist){
        for(Lead leadRec : newlist){
            if(leadRec.Industry == 'Healthcare'){
                leadRec.LeadSource = 'Purchased List';
                leadRec.SICCode__c = '1100';
                leadRec.Primary__c = 'Yes';
            }
        }
    }*/
}